build: t1 t2 t3 t4

t1:
	gcc testcase1.c -lm -lpthread -o testcase1

t2:
	gcc testcase2.c -lm -lpthread -o testcase2

t3:
	gcc testcase3.c -lm -lpthread -o testcase3

t4:
	gcc testcase4.c -lm -lpthread -o testcase4
